trigger: none

schedules:
  - cron: "*/10 * * * *"
    displayName: At every 10th minute
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

variables:
  - group: tibber-pulse

steps:
  - task: PowerShell@2
    inputs:
      filePath: $(Build.SourcesDirectory)/tibber-pulse.ps1
      pwsh: true
    displayName: Tibber Pulse
    env:
      GF_API_KEY: $(GF_API_KEY)
      AZURE_PIPELINES: true
