trigger: none

steps:
  - task: PowerShell@2
    inputs:
      filePath: $(Build.SourcesDirectory)/tibber-pulse.ps1
      pwsh: true
    displayName: Tibber Pulse
    env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)