trigger: none

schedules:
  - cron: "0 * * * *"
    displayName: At minute 0
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

resources:
  repositories:
    # See https://github.com/stefanes/azure-pipelines
    - repository: templates
      type: github
      endpoint: stefanes
      name: stefanes/azure-pipelines

jobs:
  - job:
    displayName: Tibber today's price info
    timeoutInMinutes: 50
    steps:
      - template: install-modules.yml@templates
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - template: invoke-expressionwithretry.yml@templates
        parameters:
          expression: .\tibber-price.ps1 -Today -Publish -TimeZone 'W. Europe Standard Time'
          displayName: Get today's price info metrics
          env:
            TIBBER_ACCESS_TOKEN: $(TIBBER_API_KEY)
            TIBBER_USER_AGENT: "stefanes.tibber-pulse/0.1.1"
            GRAPHITE_ACCESS_TOKEN: $(GF_API_KEY)
