trigger: none

schedules:
  - cron: "30 * * * *"
    displayName: At minute 30
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

jobs:
  - job:
    displayName: Tibber Consumption
    timeoutInMinutes: 10
    steps:
      - template: templates/install-modules.yml
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - task: PowerShell@2
        inputs:
          filePath: $(Build.SourcesDirectory)/tibber-consumption.ps1
          arguments: -Publish -Detailed
          pwsh: true
        displayName: Tibber Consumption
        retryCountOnTaskFailure: 3
        env:
          TIBBER_ACCESS_TOKEN: $(TIBBER_API_KEY)
          GRAPHITE_ACCESS_TOKEN: $(GF_API_KEY)
