trigger: none

schedules:
  - cron: "0 13 * * *"
    displayName: At 13:00 # UTC = 14:00 CET/15:00 CEST
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

resources:
  repositories:
    # See https://github.com/stefanes/azure-pipelines
    - repository: templates
      type: github
      endpoint: stefanes
      name: stefanes/azure-pipelines

jobs:
  - job:
    displayName: Tibber tomorrow's price info
    timeoutInMinutes: 30
    steps:
      - template: install-modules.yml@templates
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - pwsh: |
          & .\tibber-price.ps1 -Tomorrow -Publish -TimeZone 'W. Europe Standard Time' -Verbose -Debug
        displayName: Get tomorrow's price info metrics
        workingDirectory: $(Build.SourcesDirectory)
        retryCountOnTaskFailure: 10 # The maximum allowed number of attempts is 10
        env:
          TIBBER_ACCESS_TOKEN: $(TIBBER_API_KEY)
          GRAPHITE_ACCESS_TOKEN: $(GF_API_KEY)
