trigger: none

schedules:
  - cron: "0,30 * * * *"
    displayName: At minute 0 and 30
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

resources:
  repositories:
    # See https://github.com/stefanes/azure-pipelines
    - repository: templates
      type: github
      endpoint: stefanes
      name: stefanes/azure-pipelines

jobs:
  - job:
    displayName: Tibber live measurements
    timeoutInMinutes: 120
    steps:
      - template: install-modules.yml@templates
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - pwsh: |
          Import-Module -Name .\tibber-pulse.psd1 -Force -PassThru
          Write-Host "##[command]Get-ReadUntil"
          $until = Get-ReadUntil

          $succeedWithIssues = $false
          while ($true) {
              try {
                  & .\tibber-live.ps1 -Until $until -Publish -TimeZone 'W. Europe Standard Time'
                  break # normal exit
              }
              catch {
                  # failure, try again...
                  Write-Host "##vso[task.logissue type=warning]Keep calm and carry on... [$_]"
                  $succeedWithIssues = $true
                  #Start-Sleep -Seconds 5
              }
          }

          if ($succeedWithIssues) {
              Write-Host "##vso[task.complete result=SucceededWithIssues;]DONE"
              exit 0
          }
        displayName: Get live measurement metrics
        workingDirectory: $(Build.SourcesDirectory)
        retryCountOnTaskFailure: 10 # The maximum allowed number of attempts is 10
        env:
          TIBBER_ACCESS_TOKEN: $(TIBBER_API_KEY)
          GRAPHITE_ACCESS_TOKEN: $(GF_API_KEY)
