trigger: none

schedules:
  - cron: "0 */4 * * *"
    displayName: At minute 0 past every 4th hour
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

resources:
  repositories:
    # See https://github.com/stefanes/azure-pipelines
    - repository: templates
      type: github
      endpoint: stefanes
      name: stefanes/azure-pipelines

jobs:
  - job:
    displayName: Tibber live measurements
    timeoutInMinutes: 250
    steps:
      - template: install-modules.yml@templates
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - template: invoke-expression.yml
        parameters:
          expression: .\tibber-live.ps1 -Until $until -Publish -TimeZone 'W. Europe Standard Time'
          live: true
          displayName: Get live measurement metrics
