trigger: none

schedules:
  - cron: "30 12 * * *"
    displayName: At 12:30 # UTC = 13:30 CET/14:30 CEST
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

resources:
  repositories:
    # See https://github.com/stefanes/azure-pipelines
    - repository: templates
      type: github
      endpoint: stefanes
      name: stefanes/azure-pipelines

jobs:
  - job:
    displayName: Tibber tomorrow's price info
    steps:
      - template: install-modules.yml@templates
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - template: invoke-expression.yml
        parameters:
          expression: .\tibber-price.ps1 -Tomorrow -Publish -TimeZone 'W. Europe Standard Time'
          displayName: Get tomorrow's price info metrics
