trigger: none

schedules:
  - cron: "0 1 * * *"
    displayName: At 01:00 # UTC = 02:00 CET/03:00 CEST
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

resources:
  repositories:
    # See https://github.com/stefanes/azure-pipelines
    - repository: templates
      type: github
      endpoint: stefanes
      name: stefanes/azure-pipelines

jobs:
  - job:
    displayName: Tibber price info
    timeoutInMinutes: 50
    steps:
      - template: install-modules.yml@templates
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - template: invoke-expressionwithretry.yml@templates
        parameters:
          expression: .\tibber-price-json.ps1 -Path '$(Pipeline.Workspace)' -TimeZone 'W. Europe Standard Time' -ExcludeTomorrow
          displayName: Get price info metrics
          env:
            TIBBER_ACCESS_TOKEN: $(TIBBER_API_KEY)
            TIBBER_USER_AGENT: "stefanes.tibber-pulse/0.1.1"
            GRAPHITE_ACCESS_TOKEN: $(GF_API_KEY)
            GRAPHITE_METRICS_PREFIX: tibber

      - publish: "$(Pipeline.Workspace)/tibber-price.json"
        artifact: tibber-price
        displayName: Publish Tibber price info
