trigger: none

schedules:
  - cron: "0 * * * *"
    displayName: At minute 0
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

jobs:
  - job:
    displayName: Tibber Live
    timeoutInMinutes: 120
    steps:
      - template: templates/install-modules.yml
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - task: PowerShell@2
        inputs:
          filePath: $(Build.SourcesDirectory)/tibber-live.ps1
          arguments: -Publish -Detailed
          pwsh: true
        displayName: Tibber Live
        retryCountOnTaskFailure: 10 # The maximum allowed number of attempts is 10
        env:
          TIBBER_ACCESS_TOKEN: $(TIBBER_API_KEY)
          GRAPHITE_ACCESS_TOKEN: $(GF_API_KEY)
