trigger: none

schedules:
  - cron: "10 * * * *"
    displayName: At minute 10
    branches:
      include:
        - main
    always: true

pool:
  vmImage: windows-latest

variables:
  - group: tibber-pulse

resources:
  repositories:
    # See https://github.com/stefanes/azure-pipelines
    - repository: templates
      type: github
      endpoint: stefanes
      name: stefanes/azure-pipelines

jobs:
  - job:
    displayName: Tibber Consumption
    timeoutInMinutes: 10
    steps:
      - template: install-modules.yml@templates
        parameters:
          modules:
            - PSTibber
            - PSGraphite
          allowPrerelease: false
          reinstall: true

      - task: PowerShell@2
        inputs:
          filePath: $(Build.SourcesDirectory)/tibber-consumption.ps1
          arguments: -Publish -Detailed
          pwsh: true
        displayName: Get consumption metrics
        retryCountOnTaskFailure: 3
        env:
          TIBBER_ACCESS_TOKEN: $(TIBBER_API_KEY)
          GRAPHITE_ACCESS_TOKEN: $(GF_API_KEY)
